### ISSUE TITLE
On `secureli scan`, notify user that updated hooks are available for installation

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#176]
**User Story**
As a developer, whenever my local repo is scanned, I would like to know if any of my linters or hooks are out of date, so I can make an informed decision on whether I need to upgrade them.

**Acceptance Criteria**
- When running `secureli scan`, query for the latest released version of each pre-commit hook that is installed for the repo
  - If the installed version of each hook matches the latest released version, do not display any additional information
  - If the installed version of _any_ of the installed hooks is out of date, display a message to the user that there are hooks that can be updated

**Comment by tdurk93** [comment]
On the surface, this sounds similar to the functionality provided by `secureli update`, which updates pre-commit hooks. However, it is not possible to implement this in the same way. We implement that functionality by executing `pre-commit autoupdate`, which both checks for new commits/tags on hook repositories, and updates `.pre-commit-config.yaml` to specify any new revisions. (The new commits/tags aren't pulled down until pre-commit runs or `pre-commit install` is executed.)

In order to check for updates without performing an update, we will to take a different approach:
1. We could implement the checking of the git repositories ourselves, possibly with help from the code used by pre-commit. However, it looks to be a bit more complicated than it would first appear, so I would rather not maintain this logic in our repository.
2. Since pre-commit is written in python, we could import the necessary functions/classes directly, but this depends on non-published functionality remaining consistent
3. We could back up the config file, run `pre-commit autoupdate`, then diff the result and restore the original file.
4. We could update the `pre-commit` repo to add a dry-run feature to the `autoupdate` subcommand


Here's where the relevant code is located in the `pre-commit` repository: https://github.com/pre-commit/pre-commit/blob/2280645d0e2f1fa54654d8c36cc8d62f15f4d413/pre_commit/commands/autoupdate.py#L162

**Comment by tdurk93** [comment]
PR is here: https://github.com/slalombuild/secureli/pull/336
