### ISSUE TITLE
Since we are technically in Alpha can we fix semver to add -A to our versions?

### ISSUE THREAD

**Issue by calebtonn** [slalombuild/secureli#250]

**Comment by gabenegron** [comment]
@chrisba11 @sbates Do either of you know the answer to this question?

**Comment by calebtonn** [comment]
I did a little digging and this looks like it is depending on poetry as defined in the toml file.

**Comment by calebtonn** [comment]
https://python-poetry.org/docs/libraries#versioning

**Comment by tdurk93** [comment]
Added some commented-out code in a PR that I believe will address this: https://github.com/slalombuild/secureli/pull/366

**Comment by tdurk93** [comment]
I did a bit more research and it seems that typically pre-releases have their own version number outside of the `<major>.<minor>.<patch>` version. A typical pre-release might be `1.7-rc.3`  or 1.2.3-alpha.1`. Once the pre-release version (or release candidate) is ready for release, the pre-release suffix is dropped. Technically `1.0-alpha.3.17` is also valid by the [semantic release spec](https://semver.org/#spec-item-9), but I believe our tool for bumping the version [limits us to a single integer](https://python-semantic-release.readthedocs.io/en/latest/multibranch_releases.html) after the pre-release suffix.
For this reason I'm not sure if setting configuring our semantic-release tool to use a pre-release is the best option.

Also, poetry claims to require version strings in `pyproject.toml` that comply with [PEP440](https://peps.python.org/pep-0440/), which as far as I can tell would not allow the period following the pre-release suffix (e.g. in `-alpha.1`) which is added by `semantic-release`.

Alternatively, we could instruct our semantic-release tool to append a `-A` or `-alpha` to our git tags and in the commit message created by semantic-release where our versions are bumped in `pyproject.toml` (currently those look like this: `chore(release): Tag v{version} [skip ci]`). However, the version string in `pyproject.toml` (and the version recognized by semantic-release) would not contain the `-A`/`-alpha` suffix.

My recommendation is to either allow the versioning to remain as-is (with the leading `0` major version number indicating an unstable/pre-release status).

Otherwise we can append `-A` to our version tags (recognized by GitHub) but allow `semantic-release`/`poetry`/`PyPI` to continue recognizing the version without the `-A` suffix. This option seems more confusing to me.

**Comment by calebtonn** [comment]
I am ok leaving as is. I was only wanting to do this if it is an easy change in semantic release. Making a distinction between Alpha and Beta is more a marketing thing for us anyway. Thanks
