### ISSUE TITLE
Determine best approach for Windows support

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#46]
The secureli application currently is only supported by MacOS. We'd like to extend support over to Windows development machines. We need to align on an approach to best do that. Is this something that can be facilitated through VS extension for .NET developers? Do we just rely on PIP? Homebrew on WSL? What approach will best serve the Windows development community?

**Comment by dan-arnold** [comment]
As a C# developer, I would like to be able to use SeCureLi from within Visual Studio 2022 without having to install it and run it from the command line.

To solve this, a Visual Studio extension (VSIX) could be implemented. VSIX are written in .NET and can include menu items, contextual menu items, and even UI panes to expose the extension functionality to the user. Further discussion should occur around what the user experience for developers should be when utilizing SeCureLi from Visual Studio.

An overview of the steps involved in building a VSIX extension for SeCureLi:
* Create a VSIX project in Visual Studio
* Implement UI features
* For interacting with SeCureLi itself, which is Python, we can utilize IronPython, which is a Python runtime for .NET. We should abstract away this part of the functionality so that the VSIX could be updated in the future if the way of running SeCureLi changes.
** IronPython will allow us to call Python functions directly from .NET code.
** For example:
```
// Add a reference to the IronPython.dll and Microsoft.Scripting.dll assemblies to your project.
using IronPython.Hosting;

// ...

var var1,var2 = /* Input to SeCureLi function */
var engine = Python.CreateEngine();
var scope = engine.CreateScope();
engine.ExecuteFile(@"C:\secureli.py", scope);
dynamic testFunction = scope.GetVariable("build");
var result = testFunction("magenta");
```

This way we can call SeCureLi from the Visual Studio Extension and expose whatever functionality is needed.

Open Questions:
* How should we bundle SeCureLi, would it come with the extension installer, or would the installer download it?
* Do we need Python installed on the user's machine? I think we don't, because all the Python is being executed by IronPython.
* What should the UI and user experience be for the developer?
* Does this work? A POC should be done before jumping into full implementation.
