### ISSUE TITLE
Investigate instrumentation

### ISSUE THREAD

**Issue by calebtonn** [slalombuild/secureli#50]
We need to be able to instrument Secureli to connect to an observability backend.

Could we do this with https://opentelemetry.io/

**Comment by gabenegron** [comment]
Would like to cover the following user story as part of this effort, if possible:
_As a member of a team using secureli, I can see who added an ignore to my .secureli.yaml file and why they did so_

**Comment by gabenegron** [comment]
https://grafana.com/ may also be an option?

**Comment by calebtonn** [comment]
Grafana is an observability platform that we would want to support. The means for supporting it would be creating some kind of telemetry instrumentation that can connect to it. Open Telemetry would be one way of having a standardized connection pattern to multiple tools like Grafana.

**Comment by hartonor-slalom** [comment]
Using open telemetry and prometheus it looks like I can get the metric based on my simple python app. Something to note:
- Because prometheus is a pull based system, with ephemeral app like seCureLI, it won't get a chance to pull the data before the app stop. Thus we need to use prometheus push-gateway.
- Because we need to use prometheus push-gateway, we can't use opentelemetry metric counter, we have to use the counter sdk from prometheus
- The way we use counter, we need to retrieve the last counter value, and add + 1 to keep track of the total value, instead of just using something like counter.inc() every time, because when the app stop, counter will reset to 0. I would have thought opentel or prometheus will keep track of the total count, but it does not seems like it.

There might be a push based method with opentelemetry too, I haven't really looked into it yet.

**Comment by calebtonn** [comment]
I think we would want to use Opentelemtry Data Collection to maintain agnostic open source compatibility with other observability platforms.

https://opentelemetry.io/docs/concepts/data-collection/
