### ISSUE TITLE
Create happy path E2E test that can be run locally by developers

### ISSUE THREAD

**Issue by gabenegron** [slalombuild/secureli#53]
**Description**
This is the first step towards having end-to-end tests that run in the pipeline. The overall approach will include these items:

1. Happy path end to end test that a developer is able to run locally
2. Happy path end to end testing that is able to run in the pipeline against our secureli project
3. Happy path end to end testing that is run against repos that are majority other supported languages
4. Negative path testing for all three of the previous scenarios

This ticket only applies to step 1.

**Acceptance Criteria**
- Identify and implement a test framework to use
- Write tests to cover `secureli init` and `secureli scan`
- Update the CONTRIBUTING.md file with instructions for setting up and running the automation

**Original description for posterity:** 
To best support our development effort, the team wants to have a set of test repos which contain embedded secrets that should be caught by secureli. The pipeline should run through these test repos and ensure that the build for each one of these test repos fails as expected. Introduction of test repos for the various development languages supported by secureli will be handled by additional user stories in the backlog, but one for Python already exists.

**Acceptance Criteria**

- Pipeline changes are made, so that building test Python repo fails, and this passes the secureli pipeline build

**Comment by calebtonn** [comment]
https://canarytokens.org/generate is how I have tested secrets in the past. It is a good way of generating secrets that look real but aren't. Posting here if it helps.

**Comment by josh-at-slalom** [comment]
I believe that this will do what we need for some high-level end to end testing.
https://bats-core.readthedocs.io/en/stable/tutorial.html

Unfortunately I cannot get the bats-support and bats-assert submodules to work so that I can partially assert on the system output after running 'securli scan'. Maybe someone with more BASH experience can help me figure out what I'm doing wrong.

I will also be looking into using pytest for integration tests, but I'm not exactly sure how much additional coverage that will provide.
