### ISSUE TITLE
Prompted to ReInstall When Running on Branch

### ISSUE THREAD

**Issue by blonienc** [slalombuild/secureli#537]
As a SeCurLI user, when I run SeCureLI on a branch after initial install, I am prompted to reinstall.  
 
This causes issues in the fact that if I reinstall my YAML files will be overwritten losing the information I have already gathered and populated.  
 
To reproduce: 
- Create new repo with main (do not install SeCureLI)
- Create a branch from main
- Install and run SeCureLI on branch
- Run SeCureLI a second or more time on branch

Results: 

![Image](https://github.com/slalombuild/secureli/assets/160081144/3c8adf0d-ef0d-4eb9-94de-cce8cd75d7e9)

 
 
AC:
-              SeCurLI can be installed and ran multiple times on a branch without being prompted to reinstall
-              SeCureLI is not installed on main before running on branches
 
Open Questions:
- Can this be solutioned to also help resolve https://github.com/slalombuild/secureli/issues/522

**Comment by isaac-heist-slalom** [comment]
Issues found when looking at #537

1) Jeff's first question - "I'm seeing that `secureli init` needs to be run on each clone of the client repo, even though my `.secureli` directory and `.secureli.yaml` are committed to the repo."

![image](https://github.com/slalombuild/secureli/assets/127901972/8dc44c7e-5b5c-4d27-b85e-945a6959c5a0)

Yes, when a repo with secureli installed on it is cloned to another location, it does need to be initialized. Underlying files that are `.gitignored` and not committed are:

* `.secureli/repo-config.yaml`
* `.git/hooks/pre-commit`

Install vs initialization. Verbiage and documentation use installation for both. Should this be cleaned up to avoid confusion?

`seCureLI has not yet been installed, install now? [Y/n]:`
to
`seCureLI has not yet been initialized in this repo/directory, initialize now? [Y/n]:`

Secureli scan on repo where secureli is initialized:
![image](https://github.com/slalombuild/secureli/assets/127901972/80490654-b2d1-499c-80f0-c13964121417)

2) Initialization of repo with custom `.secureli.yaml` configs will auto format `.secureli.yaml`, even if linters were not chosen to be installed. Given that `.secureli.yaml` is a secureli file, is this expected behavior?
![image](https://github.com/slalombuild/secureli/assets/127901972/87d4e475-0319-4a4f-bcaf-1ac592f1b46a)


3) Error in main branch where secureli artifacts that are ignored by git carry over.

Says "seCureLI is installed and up-to-date for the following language(s)", even though secureli is not initialized completely in that branch.  This is not an expected workflow, but can certainly occur.

![image](https://github.com/slalombuild/secureli/assets/127901972/aabb1954-56ec-486c-a51f-bcd68ca0110e)
